name: Web Application Deployment to EKS Cluster

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask-webapp/webapp:1.0

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }} 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push the Docker Image to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 489857930706.dkr.ecr.us-east-1.amazonaws.com
        docker tag flask-webapp/webapp:1.0 489857930706.dkr.ecr.us-east-1.amazonaws.com/flask-webapp/webapp
        docker push 489857930706.dkr.ecr.us-east-1.amazonaws.com/flask-webapp/webapp:1.0
